### ISSUE TITLE
Page DataのエクスポートJSONにusersプロパティが追加されている

### ISSUE THREAD

**Issue by towa1204** [scrapbox-jp/types#57]
CosenseでPage Dataをエクスポートしたところ下記のような形式のJSONが取得されました。
usersプロパティはExportedDataインタフェースに現在いないようです。
https://github.com/scrapbox-jp/types/blob/b745ee4e6c1cc5033aa8be849901d7f964b2cbde/response.ts#L314
過去のJSONにusersプロパティは存在しなかったため新規追加されたものだと思います。

```jsonc
{
  "name": "xxx",
  "displayName": "xxx",
  "exported": "xxx",
  "users": [
    {
      "id": "xxx",
      "name": "xx",
      "displayName": "xxx",
      "email": "xxx"
    },
    // プロジェクトメンバーの数だけ存在
  ],
  "pages": [
    { 
...
```

**Comment by takker99** [comment]
@towa1204 返信が遅れてすみません！いま気づきました……

本体のAPI変更の報告ありがとうございます。助かります。
ちょうど今`globalThis.scrapbox`の型定義を現行のAPIに追随させる作業をしていたところなので、それに合わせて`ExportedData`を修正させていただきます！

**Comment by towa1204** [comment]
ありがとうございます！
非常に助かります

**Comment by takker99** [comment]
Released [0.10.4](https://jsr.io/@cosense/types@0.10.4)!
